project:
  type: website

website:
  title: "Haresh's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd

format:
  html:
    theme:
      - jolla
      - brand
    css: styles.css
    toc: true

editor: visual

